### ISSUE TITLE
get_version_from_formula: Couldn't find HOME environment

### ISSUE THREAD

**Issue by ringods** [opscode-cookbooks/homebrew#53]
I run Chef on Mac OS X via Launchd in interval mode instead of as a daemon. The ``homebrew::cask`` recipe is part of my run list, but I get the following error:

```
[2014-08-18T18:18:08+02:00] INFO: Processing package[brew-cask] action install (homebrew::cask line 22)
ESC[0m
================================================================================ESC[0m
ESC[31mError executing action `install` on resource 'package[brew-cask]'ESC[0m
================================================================================ESC[0m

ESC[0mArgumentErrorESC[0m
-------------ESC[0m
couldn't find HOME environment -- expanding `~'ESC[0m

ESC[0mCookbook Trace:ESC[0m
---------------ESC[0m
/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:89:in `get_version_from_formula'
ESC[0m/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:69:in `current_installed_version'
ESC[0m/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:39:in `load_current_resource'ESC[0m

ESC[0mResource Declaration:ESC[0m
---------------------ESC[0m
# In /var/chef/cache/cookbooks/homebrew/recipes/cask.rb
ESC[0m
ESC[0m 22: package 'brew-cask'
ESC[0m
ESC[0mCompiled Resource:ESC[0m
------------------ESC[0m
# Declared in /var/chef/cache/cookbooks/homebrew/recipes/cask.rb:22:in `from_file'
ESC[0m
ESC[0mpackage("brew-cask") do
ESC[0m  action :install
ESC[0m  retries 0
ESC[0m  retry_delay 2
ESC[0m  guard_interpreter :default
ESC[0m  package_name "brew-cask"
ESC[0m  timeout 900
ESC[0m  cookbook_name "homebrew"
ESC[0m  recipe_name "cask"
ESC[0mend
ESC[0m
ESC[0m[2014-08-18T18:18:08+02:00] INFO: Running queued delayed notifications before re-raising exception
[2014-08-18T18:18:08+02:00] ERROR: Running exception handlers
[2014-08-18T18:18:08+02:00] ERROR: Exception handlers complete
[2014-08-18T18:18:08+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-08-18T18:18:08+02:00] INFO: Sending resource update report (run-id: d837723e-bb95-4c9f-ba59-a77aa1a36a8a)
[2014-08-18T18:18:09+02:00] ERROR: package[brew-cask] (homebrew::cask line 22) had an error: ArgumentError: couldn't find HOME environment -- expanding `~'
```

In ``get_response_from_command``, the ``HOME`` variable is explicitly retrieved. Shouldn't the same be done in ``get_response_from_formula`` ??

**Comment by jtimberman** [comment]
This is fixed in [Chef 12.0.2](https://github.com/opscode/chef/blob/master/CHANGELOG.md#1202).
